"""In-memory repository used for the mock MVP."""

from collections.abc import Sequence

from backend.app.models.schemas import Document, TaskRecord


class InMemoryTaskRepository:
    """Store tasks and documents in memory for local validation."""

    def __init__(self) -> None:
        self._tasks: dict[str, TaskRecord] = {}
        self._documents_by_task: dict[str, list[Document]] = {}

    def save_task(self, task: TaskRecord) -> TaskRecord:
        """Insert or replace a task."""
        self._tasks[task.id] = task
        return task

    def get_task(self, task_id: str) -> TaskRecord | None:
        """Fetch a task by id."""
        return self._tasks.get(task_id)

    def save_documents(self, task_id: str, documents: list[Document]) -> None:
        """Persist the normalized documents for one task."""
        self._documents_by_task[task_id] = documents

    def get_documents(self, task_id: str) -> Sequence[Document]:
        """Fetch documents generated by a task."""
        return self._documents_by_task.get(task_id, [])


task_repository = InMemoryTaskRepository()
